export const GOOD_FOOD_ICON = '/img/icons/good-food.svg'
export const RESTAURANT_ICON = '/img/icons/restaurant.svg'
export const MENUS_ICON = '/img/icons/menus.svg'
export const USERS_ICON = '/img/icons/users.svg'
export const PROFILE_ICON = '/img/icons/profile.svg'
export const SEARCH_ICON = '/img/icons/search.svg'
export const EDIT_ICON = '/img/icons/edit-icon.svg'
export const DELETE_ICON = '/img/icons/delete-icon.svg'
